# This workflow triggers on a published release event.
# Requires the following secrets:
# - PAKETO_BOT_GITHUB_TOKEN -> a token with permissions to send the dispatch to the language family repo

name: Send Release Dispatch

on:
  release:
    types: [published]

jobs:

  dispatch:
    runs-on: ubuntu-latest
    name: Send Dispatch
    steps:

    - name: Parse ID and Version
      id: dependency
      run: |
        echo "::set-output name=id::$(jq -r .repository.full_name ${{ github.event_path }})"
        echo "::set-output name=version::$(jq -r .release.tag_name ${{ github.event_path }} | sed 's/^v//')"

    # Generic repository dispatch sender.
    - name: Send Repository Dispatch
      uses: paketo-buildpacks/github-config/actions/dispatch@main
      with:
        repos: paketo-community/ruby # comma-separated list of repos receiving the dispatch
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        event: dependency-update
        payload: |
          {
            "strategy": "replace",
            "dependency": {
              "id": "${{ steps.dependency.outputs.id }}",
              "version": "${{ steps.dependency.outputs.version }}"
            }
          }
